services:
  music-tag:
    build:
      context: ./music-tag-web
      dockerfile: compose/local/django/Dockerfile
    container_name: music-tag-web
    ports:
      - "8001:8001"
    volumes:
      - ./music-tag-web:/app
      - ./config:/app/data
      - /home/godke/Data/MusicDB:/app/media

    command: /start
    restart: always
